[package]
name = "fmusim"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8.8"
clap = { version = "4.5.54", features = ["derive"] }
fmi-rs = { path = "../fmi-rs/fmi-rs" }
fmi-rs-cvode = { path = "../fmi-rs/fmi-rs-cvode" }
fmi-rs-xsd = { path = "../fmi-rs/fmi-rs-xsd" }
zip = "2.1"
tempfile = "3.8"
csv = "1.4.0"
colored = "3.1.1"
plotly = "0.14.1"
term_size = "0.3"
roxmltree = "0.21.1"


[dev-dependencies]
rstest = "0.26.1"
