[package]
name = "BouncingBall"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
fmi = { path = "../fmi" }
fmi-export = { path = "../fmi-export" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
static_vcruntime = "2.0"

[features]
fmi2 = []